version: '3.8'

services:
  couchpotato-python2:
    build:
      context: .
      dockerfile: Dockerfile.python2
    container_name: couchpotato-python2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      # Configuration and database
      - ./data/config:/config
      - ./data/app_data:/data
      # Media directories - update these paths to match your setup
      - ./data/downloads:/downloads
      - ./data/movies:/movies
    ports:
      - "5050:5050"
    restart: unless-stopped
    networks:
      - couchpotato-network

networks:
  couchpotato-network:
    driver: bridge