"""The browser session is an HMAC-signed token, not the api_key.

Before this change the `user` cookie held `Env.setting('api_key')` verbatim, so
the browser's session cookie WAS the credential `/api/{route:path}`
authenticates with. Anyone who read it could add, rename and delete the
library, logout could only ask the browser to forget a value the thief already
had, and the only revocation was rotating the api_key -- which breaks the
userscript and every downloader at the same time, so in practice it never
happened.

This file covers the pure seam only: mint a token, verify a token, generate a
secret. Every one of them takes the clock and the secret as arguments (AC-QA-26),
so expiry is provable without `sleep`, without a running server, and without
patching module-level `time.time` -- which this repo has a recorded false
positive from, because patching `module.time.time` also freezes `date.today()`.

Persistence, the startup bootstrap and the request path live in
`test_session_secret_store.py`.
"""
import ast
import inspect
import re
import textwrap

import pytest

from couchpotato import (
    SESSION_COOKIE_NAME,
    SESSION_LIFETIME,
    SESSION_LIFETIME_REMEMBERED,
    SESSION_SECRET_PROPERTY,
    generate_session_secret,
    mint_session_token,
    verify_session_token,
)

# A fixed secret, so a failure is reproducible. Shaped like the real thing
# (64 hex characters = 32 bytes) but never generated by the production code, so
# nothing here can accidentally depend on the generator.
SECRET = 'a' * 64
OTHER_SECRET = 'b' * 64
NOW = 1_700_000_000


def implementation_of(function) -> str:
    """The function's CODE, with its docstring and comments removed.

    A raw `inspect.getsource` check is unusable here because the prose has to
    name what it forbids: the docstring of `generate_session_secret` mentions
    `uuid4` and `md5` precisely to say they are banned, and a substring check
    would fire on the explanation. Deleting `__doc__` textually is not the
    answer either -- Python 3.14 dedents docstrings, so `__doc__` is no longer
    a substring of the source and the strip silently stops working, leaving a
    guard that passes for the wrong reason on one interpreter and fails on
    another.
    """
    tree = ast.parse(textwrap.dedent(inspect.getsource(function)))
    statements = tree.body[0].body
    if (statements and isinstance(statements[0], ast.Expr)
            and isinstance(statements[0].value, ast.Constant)
            and isinstance(statements[0].value.value, str)):
        statements = statements[1:]
    return '\n'.join(ast.unparse(node) for node in statements)


class TestTheSeamIsInjectable:
    """AC-QA-26: one importable seam, clock and secret both injectable."""

    def test_mint_and_verify_take_an_injected_clock_and_secret(self):
        token = mint_session_token(SECRET, SESSION_LIFETIME, now=NOW)

        assert verify_session_token(token, SECRET, now=NOW + 1) is True

    def test_no_module_level_clock_patching_is_required_to_move_time(self):
        """The whole point of the injected clock: 30 days pass in one line."""
        token = mint_session_token(SECRET, SESSION_LIFETIME, now=NOW)

        assert verify_session_token(token, SECRET, now=NOW + 30 * 24 * 3600) is False

    def test_verification_is_a_pure_function_of_its_arguments(self):
        """Same inputs, same answer, no hidden state between calls."""
        token = mint_session_token(SECRET, SESSION_LIFETIME, now=NOW)

        assert [verify_session_token(token, SECRET, now=NOW + 5) for _ in range(3)] == [True] * 3


class TestSecretGeneration:
    """AC-SEC-32: `secrets`, at least 32 bytes, never derived from anything."""

    def test_the_secret_carries_at_least_32_bytes_of_entropy(self):
        secret = generate_session_secret()

        assert re.fullmatch(r'[0-9a-f]+', secret), (
            'the secret must be hex text: it round-trips through the property '
            'store, whose setProperty() calls toUnicode() and decodes with '
            'replacement, so raw bytes come back MANGLED (measured: 32 bytes '
            'in, 29 characters out, and the surviving length varies with the '
            'random bytes). Got %r' % secret
        )
        assert len(bytes.fromhex(secret)) >= 32, (
            'only %d bytes of entropy' % len(bytes.fromhex(secret))
        )

    def test_two_fresh_installs_do_not_share_a_secret(self):
        secrets_seen = {generate_session_secret() for _ in range(20)}

        assert len(secrets_seen) == 20, 'the generator repeated itself'

    def test_the_generator_is_the_secrets_module(self):
        """`inspect.getsource`, the idiom at tests/unit/test_http_client.py:244.

        Asserted at the source because the output of a bad generator looks
        exactly like the output of a good one: `md5(api_key)` is 32 hex
        characters too, and every property test above would still pass while
        the secret was derivable by anyone holding the api_key.
        """
        body = implementation_of(generate_session_secret)

        assert 'secrets.' in body, (
            'the session secret must come from the `secrets` module; the '
            'implementation is:\n%s' % body
        )
        for forbidden in ('uuid4', 'md5', 'random.', 'time.time', 'api_key',
                          'password', 'getrandbits'):
            assert forbidden not in body, (
                'the session secret is derived from %r. A secret derived from '
                'anything an attacker can read or guess is not a secret: the '
                'api_key is embedded in every rendered page, and deriving from '
                'it would make session forgery permanent and survive every '
                'api_key rotation.\nimplementation is:\n%s' % (forbidden, body)
            )


class TestForgeryIsRefused:
    """AC-SEC-31, one named test per shape.

    Deliberately NOT a loop over one assertion: a loop reports the first
    failure and stops, so the five shapes after it stay unproven, and a
    regression in the last shape reads as the same red as a regression in the
    first.
    """

    @pytest.fixture
    def token(self):
        return mint_session_token(SECRET, SESSION_LIFETIME, now=NOW)

    def test_a_token_with_no_signature_at_all_is_refused(self, token):
        payload = token.split('.')[0]

        assert verify_session_token(payload, SECRET, now=NOW) is False

    def test_a_token_with_an_empty_signature_is_refused(self, token):
        payload = token.split('.')[0]

        assert verify_session_token(payload + '.', SECRET, now=NOW) is False

    def test_a_truncated_signature_is_refused(self, token):
        payload, signature = token.split('.', 1)

        assert verify_session_token('%s.%s' % (payload, signature[:-1]), SECRET, now=NOW) is False

    def test_a_signature_from_a_different_secret_is_refused(self):
        forged = mint_session_token(OTHER_SECRET, SESSION_LIFETIME, now=NOW)

        assert verify_session_token(forged, SECRET, now=NOW) is False

    def test_a_mutated_payload_keeping_the_original_signature_is_refused(self, token):
        """The attack the signature exists to stop: extend your own expiry."""
        payload, signature = token.split('.', 1)
        extended = str(int(payload) + 10 * 365 * 24 * 3600)

        assert verify_session_token('%s.%s' % (extended, signature), SECRET, now=NOW) is False

    def test_a_signature_that_is_just_the_payload_repeated_is_refused(self, token):
        payload = token.split('.')[0]

        assert verify_session_token('%s.%s' % (payload, payload), SECRET, now=NOW) is False


class TestTheComparisonIsConstantTime:
    """AC-SEC-34."""

    def test_the_signature_is_compared_with_hmac_compare_digest(self):
        source = implementation_of(verify_session_token)

        assert 'hmac.compare_digest' in source, (
            'the signature comparison must be constant-time. A plain `==` '
            'short-circuits on the first differing byte, which leaks the '
            'correct signature one byte at a time to anyone who can time the '
            'response.\nsource is:\n%s' % source
        )
        assert not re.search(r'signature\s*==', source), (
            'a plain `==` on the signature defeats the constant-time '
            'comparison above it.\nsource is:\n%s' % source
        )


class TestExpiryIsEnforcedByTheServer:
    """AC-SEC-35: the expiry lives INSIDE the signed payload.

    `Max-Age` and `Expires` are requests to the browser, not enforcement. A
    replay strips them for free.
    """

    @pytest.mark.parametrize('lifetime,label', [
        (SESSION_LIFETIME, '24 hours, no remember-me'),
        (SESSION_LIFETIME_REMEMBERED, '30 days, remember-me ticked'),
    ])
    def test_just_inside_the_lifetime_is_accepted(self, lifetime, label):
        token = mint_session_token(SECRET, lifetime, now=NOW)

        assert verify_session_token(token, SECRET, now=NOW + lifetime - 1) is True, (
            'a session was refused one second BEFORE its %s lifetime ran out' % label
        )

    @pytest.mark.parametrize('lifetime,label', [
        (SESSION_LIFETIME, '24 hours, no remember-me'),
        (SESSION_LIFETIME_REMEMBERED, '30 days, remember-me ticked'),
    ])
    def test_just_outside_the_lifetime_is_refused(self, lifetime, label):
        token = mint_session_token(SECRET, lifetime, now=NOW)

        assert verify_session_token(token, SECRET, now=NOW + lifetime) is False, (
            'a session outlived its %s lifetime' % label
        )

    def test_an_expired_token_is_refused_however_the_client_replays_it(self):
        """The cookie attributes are gone by the time we see it.

        A replayed request carries only `Cookie: user=<value>` -- there is no
        `Max-Age` and no `Expires` on the way IN. If the expiry were not signed
        into the payload the server would have nothing to check.
        """
        token = mint_session_token(SECRET, SESSION_LIFETIME, now=NOW)
        expired_at = int(token.split('.')[0])

        assert verify_session_token(token, SECRET, now=expired_at + 1) is False

    def test_the_two_lifetimes_are_the_ones_D3_settled(self):
        assert SESSION_LIFETIME == 24 * 3600
        assert SESSION_LIFETIME_REMEMBERED == 30 * 24 * 3600


class TestHostileTokenValuesDoNotRaise:
    """Verification is reached by anything a client puts in a cookie."""

    @pytest.mark.parametrize('value', [
        '', '.', 'nodots', '.' * 10, 'é', 'a\x00b', '123.é',
        'not-base64!!.also-not', '9' * 400, 'x' * 100_000,
        str(NOW + 60) + '.' + 'A' * 100_000,
    ])
    def test_a_hostile_cookie_value_is_refused_rather_than_raising(self, value):
        assert verify_session_token(value, SECRET, now=NOW) is False

    @pytest.mark.parametrize('value', [None, 12345, b'bytes', ['list']])
    def test_a_non_string_cookie_value_is_refused_rather_than_raising(self, value):
        assert verify_session_token(value, SECRET, now=NOW) is False


class TestTheSecretIsNeverOptional:
    """AC-SEC-33: never sign or verify with '' / None / a constant fallback."""

    @pytest.mark.parametrize('missing', [None, '', 0, False])
    def test_verification_refuses_everything_when_the_secret_is_missing(self, missing):
        token = mint_session_token(SECRET, SESSION_LIFETIME, now=NOW)

        assert verify_session_token(token, missing, now=NOW) is False, (
            'a token verified against a %r secret. Falling back to an empty '
            'or constant key makes every install forgeable by anyone who '
            'reads this source.' % (missing,)
        )

    @pytest.mark.parametrize('missing', [None, '', 0, False])
    def test_minting_refuses_to_sign_with_a_missing_secret(self, missing):
        with pytest.raises(ValueError):
            mint_session_token(missing, SESSION_LIFETIME, now=NOW)

    def test_a_token_minted_with_an_empty_secret_is_not_accidentally_valid(self):
        """Belt and braces: even if something upstream produced one."""
        assert verify_session_token('%d.' % (NOW + 60), '', now=NOW) is False


class TestThePayloadCarriesNothingElse:
    """AC-SIMP-7: an expiry and its signature. No version, id, user or IP."""

    def test_the_token_is_exactly_an_expiry_and_a_signature(self):
        token = mint_session_token(SECRET, SESSION_LIFETIME, now=NOW)

        parts = token.split('.')
        assert len(parts) == 2, (
            'the token has %d dot-separated parts; AC-SIMP-7 allows exactly '
            'two (expiry, signature). Got %r' % (len(parts), token)
        )
        assert parts[0] == str(NOW + SESSION_LIFETIME), (
            'the first part must be the absolute expiry, so the server can '
            'enforce it. Got %r' % parts[0]
        )

    def test_the_token_carries_no_username_no_session_id_and_no_version(self):
        token = mint_session_token(SECRET, SESSION_LIFETIME, now=NOW)
        payload = token.split('.')[0]

        assert payload.isdigit(), (
            'the payload is not a bare timestamp, so it carries something '
            'else: %r. A username, a client IP or a user-agent in the cookie '
            'is personal data this project has no reason to persist, and a '
            'version prefix is a compatibility path AC-SIMP-7 forbids.' % payload
        )

    def test_the_cookie_value_is_safe_to_put_in_a_set_cookie_header(self):
        """No quoting, no separators, no whitespace -- so nothing re-encodes it."""
        token = mint_session_token(SECRET, SESSION_LIFETIME_REMEMBERED, now=NOW)

        assert re.fullmatch(r'[A-Za-z0-9._~-]+', token), (
            'the token contains a character that a Set-Cookie header would '
            'quote or a proxy would re-encode: %r' % token
        )


class TestTheNamesAreSharedConstants:
    """AC-ARCH-2: one literal each, so a rename cannot half-land."""

    def test_the_cookie_name_is_the_one_the_browser_already_holds(self):
        assert SESSION_COOKIE_NAME == 'user', (
            'renaming the cookie signs out every currently-logged-in operator '
            'on upgrade for no benefit'
        )

    def test_the_secret_property_key_is_not_the_cookie_name(self):
        assert SESSION_SECRET_PROPERTY != SESSION_COOKIE_NAME
        assert SESSION_SECRET_PROPERTY
