name: Publish

on:
  push:
    tags:
      - 'testpypi-*'
      - 'v*'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build toml

      - name: Inject version from tag
        run: |
          TAG="${GITHUB_REF_NAME}"
          # Strip prefixes like v1.2.3 or testpypi-1.2.3
          if [[ "$TAG" == v* ]]; then VER="${TAG#v}"; else VER="${TAG#testpypi-}"; fi
          echo "Setting version=$VER from tag=$TAG"
          python -c "import toml, sys; from pathlib import Path; p = Path('pyproject.toml'); d = toml.loads(p.read_text()); d['project']['version'] = sys.argv[1]; p.write_text(toml.dumps(d))" "$VER"

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to TestPyPI
        if: startsWith(github.ref_name, 'testpypi-')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: startsWith(github.ref_name, 'v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

